version: "3.6"

x-airflow-common:
  &airflow-common
  image: airflow-base:latest
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.default'
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs/airflow:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-50000}"
  depends_on:
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
  postgres-db-volume:

services:
  # olap:
  #   container_name: olap
  #   image: postgres:10.10-alpine
  #   restart: always
  #   env_file: .env
  #   healthcheck:
  #     test: pg_isready -U postgres
  #     interval: 5s
  #     retries: 5
  #     timeout: 3s
  #   ports:
  #     - 5432:5432
  #   logging:
  #     driver: none
  
  # postgrest:
    # container_name: postgrest
    # image: postgrest
    # restart: always
    # ports:
    #   - 3000:3000
    # depends_on:
    #   - olap
    # logging:
    #   driver: none

  
  
  #########################  SPARK + JUPYTERLAB  #########################
  spark-master:
    image: spark-master:latest
    container_name: spark-master
    ports:
      - 8081:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace

  spark-worker-1:
    image: spark-worker:latest
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8082:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  spark-worker-2:
    image: spark-worker:latest
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8083:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  jupyterlab:
    image: jupyterlab:latest
    container_name: spark-jupyterlab
    ports:
      - 8888:8888
    volumes:
      - shared-workspace:/opt/workspace
      - ./notebooks/:/opt/workspace/notebooks
      - ./plugins/:/opt/workspace/plugins
  #########################  SPARK + JUPYTERLAB  #########################
  
  #########################   AIRFLOW  CLUSTER   #########################
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always
    logging:
      driver: none

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always
    logging:
      driver: none

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs/airflow:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./airflow_webserver_config.py:/opt/airflow/webserver_config.py

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-worker:
    <<: *airflow-common
    command: celery worker
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}

  flower:
    <<: *airflow-common
    command: celery flower
    ports:
      - 5555:5555
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    logging:
      driver: none
  #########################   AIRFLOW  CLUSTER   #########################

  #########################          QAS         #########################
  check-black:
    image: qas-base:latest
    entrypoint: python -m black .
    volumes:
      - ./dags/:/opt/workspace/dags/
      - ./plugins/:/opt/workspace/plugins/
      - ./tests/:/opt/workspace/tests/
      - ./notebooks/:/opt/workspace/notebooks/

  check-autoflake:
    image: qas-base:latest
    entrypoint: python -m autoflake -c --remove-unused-variables --remove-all-unused-imports -r dags plugins tests
    volumes:
      - ./dags/:/opt/workspace/dags/
      - ./plugins/:/opt/workspace/plugins/
      - ./tests/:/opt/workspace/tests/

  unit-tests:
    image: qas-base:latest
    entrypoint: python -m pytest
    volumes:
      - ./coverage.xml:/opt/workspace/coverage.xml
  #########################          QAS         #########################
