ARG DEBIAN_IMAGE_TAG=11-jre-slim

FROM openjdk:${DEBIAN_IMAGE_TAG}

ARG CLUSTER_SHARED_WORKSPACE=/opt/workspace

RUN mkdir -p ${CLUSTER_SHARED_WORKSPACE}

ENV SHARED_WORKSPACE=${CLUSTER_SHARED_WORKSPACE}

# Hadoop Shared Volume Simulation
VOLUME ${CLUSTER_SHARED_WORKSPACE}

CMD ["bash"]
